name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: ${{ matrix.build-mode }} build on ${{ matrix.host }}
    runs-on: ${{ matrix.host }}
    strategy:
      fail-fast: true
      matrix:
        host: [ubuntu-18.04, ubuntu-20.04]
        build-mode: [release-safe, release-small]
        zig-version: [0.9.1]
    # env:
    #   ZIG_DIR: $HOME/zig
    #   ZIG_VERSION: 0.9.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: ${{ matrix.zig-version }}
      - name: Setup Zigmod
        uses: nektro/actions-setup-zigmod@v1.0.0
      - name: Print licenses
        run: zigmod license
      - name: Fetch dependencies and generate deps.zig
        # https://github.com/nektro/zigmod/blob/master/docs/deps.zig.md
        run: zigmod ci
      # - name: Debug zig version
      #   run: which zig && zig version
      - name: Build the path tracer in ${{ matrix.build-mode }}
        run: zig build -D${{ matrix.build-mode }}
      - name: Run tests
        run: zig build test
